apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-dns
  namespace: default
  labels:
    app: private-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: private-dns
  namespace: default
  labels:
    app: private-dns
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: private-dns
  namespace: default
  labels:
    app: private-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: private-dns
subjects:
  - kind: ServiceAccount
    name: private-dns
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-dns
  namespace: default
  labels:
    app: private-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-dns
  template:
    metadata:
      labels:
        app: private-dns
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: dns-account
            defaultMode: 256
      serviceAccountName: private-dns
      restartPolicy: Always
      containers:
        - name: private-dns
          image: tanelmae/gke-private-dns:latest
          imagePullPolicy: Always
          args:
            - "-namespace"
            - "default"
            - "-label"
            - "scope=global"
            - "-zone"
            - "my-zone"
            - "-domain"
            - "my.domain.space"
            - "-sa-file"
            - "/account/dns-account.json"
            - "-debug"
            - "true"
          volumeMounts:
            - name: service-account
              mountPath: "/account"
